"""add bp21 extra slip fields

Revision ID: 4a3a0b885918
Revises: 8d2d6e9c4a10
Create Date: 2026-07-05 15:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types may appear in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a3a0b885918"
down_revision: str | None = "8d2d6e9c4a10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("recipient_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("ptkp_status", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("previous_gross_income", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("gross_income", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("dpp_rate_basis_points", sa.Integer(), nullable=False, server_default="10000"),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("kap_kjs", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("document_number", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("document_date", sa.Date(), nullable=True),
    )
    op.add_column(
        "bp21_withholding_slips",
        sa.Column("document_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    )
    op.alter_column("bp21_withholding_slips", "previous_gross_income", server_default=None)
    op.alter_column("bp21_withholding_slips", "gross_income", server_default=None)
    op.alter_column("bp21_withholding_slips", "dpp_rate_basis_points", server_default=None)


def downgrade() -> None:
    op.drop_column("bp21_withholding_slips", "document_nitku")
    op.drop_column("bp21_withholding_slips", "document_date")
    op.drop_column("bp21_withholding_slips", "document_number")
    op.drop_column("bp21_withholding_slips", "document_type")
    op.drop_column("bp21_withholding_slips", "kap_kjs")
    op.drop_column("bp21_withholding_slips", "dpp_rate_basis_points")
    op.drop_column("bp21_withholding_slips", "gross_income")
    op.drop_column("bp21_withholding_slips", "previous_gross_income")
    op.drop_column("bp21_withholding_slips", "ptkp_status")
    op.drop_column("bp21_withholding_slips", "recipient_nitku")
