"""add bp26 withholding slips

Revision ID: 6c1f2b7d3e55
Revises: 4a3a0b885918
Create Date: 2026-07-05 16:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types may appear in autogenerated ops)
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c1f2b7d3e55"
down_revision: str | None = "4a3a0b885918"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

bp26_status = postgresql.ENUM(
    "draft", "issued", "invalid", name="bp26_status", create_type=False
)
bp26_tax_nature = postgresql.ENUM(
    "final", "non_final", name="bp26_tax_nature", create_type=False
)
bp26_tax_facility = postgresql.ENUM(
    "none", "dtp", "skb", "rate_0", name="bp26_tax_facility", create_type=False
)
bp26_spt_flag = postgresql.ENUM(
    "reported_in_spt",
    "objection_in_progress",
    "objection_completed",
    "objection_rejected_formal",
    "objection_withdrawal_review",
    "objection_withdrawal_accepted",
    "spt_audited",
    "spt_legal_process",
    name="bp26_spt_flag",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    bp26_status.create(bind, checkfirst=True)
    bp26_tax_nature.create(bind, checkfirst=True)
    bp26_tax_facility.create(bind, checkfirst=True)
    bp26_spt_flag.create(bind, checkfirst=True)

    op.create_table(
        "bp26_withholding_slips",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("siswa_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("status", bp26_status, nullable=False),
        sa.Column("withholding_number", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalid_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("spt_flag", bp26_spt_flag, nullable=True),
        sa.Column("tax_month", sa.Integer(), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column(
            "electronic_signature_status",
            sqlmodel.sql.sqltypes.AutoString(length=40),
            nullable=False,
        ),
        sa.Column(
            "recipient_identity_number",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("recipient_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("tax_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("tax_object_code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("tax_object_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("tax_nature", bp26_tax_nature, nullable=False),
        sa.Column("tax_facility", bp26_tax_facility, nullable=False),
        sa.Column("gross_income", sa.Integer(), nullable=False),
        sa.Column("dpp", sa.Integer(), nullable=False),
        sa.Column("dpp_rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("income_tax", sa.Integer(), nullable=False),
        sa.Column("kap_kjs", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("document_number", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("document_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("teacher_feedback", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["siswa_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bp26_withholding_slips_class_id"), "bp26_withholding_slips", ["class_id"])
    op.create_index(op.f("ix_bp26_withholding_slips_created_by_id"), "bp26_withholding_slips", ["created_by_id"])
    op.create_index(op.f("ix_bp26_withholding_slips_siswa_id"), "bp26_withholding_slips", ["siswa_id"])
    op.create_index(op.f("ix_bp26_withholding_slips_status"), "bp26_withholding_slips", ["status"])
    op.create_index(op.f("ix_bp26_withholding_slips_spt_flag"), "bp26_withholding_slips", ["spt_flag"])
    op.create_index(op.f("ix_bp26_withholding_slips_tax_month"), "bp26_withholding_slips", ["tax_month"])
    op.create_index(op.f("ix_bp26_withholding_slips_tax_year"), "bp26_withholding_slips", ["tax_year"])
    op.create_index(op.f("ix_bp26_withholding_slips_tenant_id"), "bp26_withholding_slips", ["tenant_id"])
    op.create_index(
        op.f("ix_bp26_withholding_slips_withholding_number"),
        "bp26_withholding_slips",
        ["withholding_number"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_bp26_withholding_slips_withholding_number"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_tenant_id"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_tax_year"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_tax_month"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_spt_flag"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_status"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_siswa_id"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_created_by_id"), table_name="bp26_withholding_slips")
    op.drop_index(op.f("ix_bp26_withholding_slips_class_id"), table_name="bp26_withholding_slips")
    op.drop_table("bp26_withholding_slips")

    bind = op.get_bind()
    bp26_spt_flag.drop(bind, checkfirst=True)
    bp26_tax_facility.drop(bind, checkfirst=True)
    bp26_tax_nature.drop(bind, checkfirst=True)
    bp26_status.drop(bind, checkfirst=True)
