"""add bp23 slip type

Revision ID: 7638529e4ebf
Revises: 25c389d80451
Create Date: 2026-08-12 06:44:41.700099

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlmodel  # noqa: F401  (SQLModel column types may appear in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7638529e4ebf'
down_revision: str | None = '25c389d80451'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE slip_type ADD VALUE 'bp23'")

def downgrade() -> None:
    pass
