"""add bp21 withholding slips

Revision ID: 8d2d6e9c4a10
Revises: 2a9ed018d6a8
Create Date: 2026-07-05 14:10:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types may appear in autogenerated ops)
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d2d6e9c4a10"
down_revision: str | None = "2a9ed018d6a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

bp21_status = postgresql.ENUM(
    "draft", "issued", "invalid", name="bp21_status", create_type=False
)
bp21_tax_nature = postgresql.ENUM(
    "final", "non_final", name="bp21_tax_nature", create_type=False
)
bp21_tax_facility = postgresql.ENUM(
    "none", "dtp", "skb", "rate_0", name="bp21_tax_facility", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    bp21_status.create(bind, checkfirst=True)
    bp21_tax_nature.create(bind, checkfirst=True)
    bp21_tax_facility.create(bind, checkfirst=True)

    op.create_table(
        "bp21_withholding_slips",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("siswa_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("status", bp21_status, nullable=False),
        sa.Column("withholding_number", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalid_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("tax_month", sa.Integer(), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column(
            "electronic_signature_status",
            sqlmodel.sql.sqltypes.AutoString(length=40),
            nullable=False,
        ),
        sa.Column("withholder_npwp", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("withholder_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
        sa.Column("withholder_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column(
            "recipient_identity_number",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("recipient_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("recipient_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("tax_object_code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("income_type", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("tax_nature", bp21_tax_nature, nullable=False),
        sa.Column("tax_facility", bp21_tax_facility, nullable=False),
        sa.Column("dpp", sa.Integer(), nullable=False),
        sa.Column("rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("income_tax", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("teacher_feedback", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["siswa_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bp21_withholding_slips_class_id"), "bp21_withholding_slips", ["class_id"])
    op.create_index(op.f("ix_bp21_withholding_slips_created_by_id"), "bp21_withholding_slips", ["created_by_id"])
    op.create_index(op.f("ix_bp21_withholding_slips_siswa_id"), "bp21_withholding_slips", ["siswa_id"])
    op.create_index(op.f("ix_bp21_withholding_slips_status"), "bp21_withholding_slips", ["status"])
    op.create_index(op.f("ix_bp21_withholding_slips_tax_month"), "bp21_withholding_slips", ["tax_month"])
    op.create_index(op.f("ix_bp21_withholding_slips_tax_year"), "bp21_withholding_slips", ["tax_year"])
    op.create_index(op.f("ix_bp21_withholding_slips_tenant_id"), "bp21_withholding_slips", ["tenant_id"])
    op.create_index(
        op.f("ix_bp21_withholding_slips_withholding_number"),
        "bp21_withholding_slips",
        ["withholding_number"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_bp21_withholding_slips_withholding_number"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_tenant_id"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_tax_year"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_tax_month"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_status"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_siswa_id"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_created_by_id"), table_name="bp21_withholding_slips")
    op.drop_index(op.f("ix_bp21_withholding_slips_class_id"), table_name="bp21_withholding_slips")
    op.drop_table("bp21_withholding_slips")

    bind = op.get_bind()
    bp21_tax_facility.drop(bind, checkfirst=True)
    bp21_tax_nature.drop(bind, checkfirst=True)
    bp21_status.drop(bind, checkfirst=True)
