"""merge bp21/bp26 tables into one withholding_slips table

BP21 and BP26 share one simulated e-Bupot form with different data values;
slip_type discriminates. Rows are copied over with fresh ids (old ids remain
embedded in already-issued withholding_number strings — cosmetic only).

Revision ID: 9e4f7a1c3b20
Revises: 6c1f2b7d3e55
Create Date: 2026-07-08 10:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types may appear in autogenerated ops)
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e4f7a1c3b20"
down_revision: str | None = "6c1f2b7d3e55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

slip_type = postgresql.ENUM("bp21", "bp26", name="slip_type", create_type=False)
slip_status = postgresql.ENUM("draft", "issued", "invalid", name="slip_status", create_type=False)
slip_tax_nature = postgresql.ENUM("final", "non_final", name="slip_tax_nature", create_type=False)
slip_tax_facility = postgresql.ENUM(
    "none", "dtp", "skb", "rate_0", name="slip_tax_facility", create_type=False
)
slip_spt_flag = postgresql.ENUM(
    "reported_in_spt",
    "objection_in_progress",
    "objection_completed",
    "objection_rejected_formal",
    "objection_withdrawal_review",
    "objection_withdrawal_accepted",
    "spt_audited",
    "spt_legal_process",
    name="slip_spt_flag",
    create_type=False,
)

OLD_ENUM_TYPES = (
    "bp21_status",
    "bp21_tax_nature",
    "bp21_tax_facility",
    "bp26_status",
    "bp26_tax_nature",
    "bp26_tax_facility",
    "bp26_spt_flag",
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in (slip_type, slip_status, slip_tax_nature, slip_tax_facility, slip_spt_flag):
        enum.create(bind, checkfirst=True)

    op.create_table(
        "withholding_slips",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slip_type", slip_type, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("siswa_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("status", slip_status, nullable=False),
        sa.Column("withholding_number", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalid_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("spt_flag", slip_spt_flag, nullable=True),
        sa.Column("tax_month", sa.Integer(), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("electronic_signature_status", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("withholder_npwp", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("withholder_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
        sa.Column("withholder_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("recipient_identity_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("recipient_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("recipient_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("recipient_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("ptkp_status", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("tax_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
        sa.Column("tax_object_code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("tax_object_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
        sa.Column("income_type", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
        sa.Column("tax_nature", slip_tax_nature, nullable=False),
        sa.Column("tax_facility", slip_tax_facility, nullable=False),
        sa.Column("previous_gross_income", sa.Integer(), nullable=False),
        sa.Column("gross_income", sa.Integer(), nullable=False),
        sa.Column("dpp", sa.Integer(), nullable=False),
        sa.Column("dpp_rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("income_tax", sa.Integer(), nullable=False),
        sa.Column("kap_kjs", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("document_number", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("document_nitku", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("teacher_feedback", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["siswa_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in (
        "slip_type",
        "tenant_id",
        "class_id",
        "siswa_id",
        "created_by_id",
        "status",
        "spt_flag",
        "tax_month",
        "tax_year",
    ):
        op.create_index(op.f(f"ix_withholding_slips_{column}"), "withholding_slips", [column])
    op.create_index(
        op.f("ix_withholding_slips_withholding_number"),
        "withholding_slips",
        ["withholding_number"],
        unique=True,
    )

    # Copy data; ids are re-assigned by the new sequence.
    op.execute(
        """
        INSERT INTO withholding_slips (
            slip_type, tenant_id, class_id, siswa_id, created_by_id,
            status, withholding_number, issued_at, invalid_reason,
            tax_month, tax_year, electronic_signature_status,
            withholder_npwp, withholder_name, withholder_nitku,
            recipient_identity_number, recipient_name, recipient_address, recipient_nitku,
            ptkp_status, tax_object_code, income_type, tax_nature, tax_facility,
            previous_gross_income, gross_income, dpp, dpp_rate_basis_points,
            rate_basis_points, income_tax, kap_kjs,
            document_type, document_number, document_date, document_nitku,
            score, teacher_feedback, created_at, updated_at
        )
        SELECT
            'bp21', tenant_id, class_id, siswa_id, created_by_id,
            status::text::slip_status, withholding_number, issued_at, invalid_reason,
            tax_month, tax_year, electronic_signature_status,
            withholder_npwp, withholder_name, withholder_nitku,
            recipient_identity_number, recipient_name, recipient_address, recipient_nitku,
            ptkp_status, tax_object_code, income_type,
            tax_nature::text::slip_tax_nature, tax_facility::text::slip_tax_facility,
            previous_gross_income, gross_income, dpp, dpp_rate_basis_points,
            rate_basis_points, income_tax, kap_kjs,
            document_type, document_number, document_date, document_nitku,
            score, teacher_feedback, created_at, updated_at
        FROM bp21_withholding_slips
        ORDER BY id
        """
    )
    op.execute(
        """
        INSERT INTO withholding_slips (
            slip_type, tenant_id, class_id, siswa_id, created_by_id,
            status, withholding_number, issued_at, invalid_reason, spt_flag,
            tax_month, tax_year, electronic_signature_status,
            recipient_identity_number, recipient_name,
            tax_type, tax_object_code, tax_object_name, tax_nature, tax_facility,
            previous_gross_income, gross_income, dpp, dpp_rate_basis_points,
            rate_basis_points, income_tax, kap_kjs,
            document_type, document_number, document_date, document_nitku,
            score, teacher_feedback, created_at, updated_at
        )
        SELECT
            'bp26', tenant_id, class_id, siswa_id, created_by_id,
            status::text::slip_status, withholding_number, issued_at, invalid_reason,
            spt_flag::text::slip_spt_flag,
            tax_month, tax_year, electronic_signature_status,
            recipient_identity_number, recipient_name,
            tax_type, tax_object_code, tax_object_name,
            tax_nature::text::slip_tax_nature, tax_facility::text::slip_tax_facility,
            0, gross_income, dpp, dpp_rate_basis_points,
            rate_basis_points, income_tax, kap_kjs,
            document_type, document_number, document_date, document_nitku,
            score, teacher_feedback, created_at, updated_at
        FROM bp26_withholding_slips
        ORDER BY id
        """
    )

    op.drop_table("bp21_withholding_slips")
    op.drop_table("bp26_withholding_slips")
    for type_name in OLD_ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")


def downgrade() -> None:
    raise NotImplementedError(
        "Merge of bp21/bp26 tables is one-way (dev-stage schema consolidation)"
    )
